allow-lan: true
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
log-level: info
mixed-port: 7890
mode: rule
proxies:
- cipher: aes-128-gcm
  name: '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡­ğŸ‡° é¦™æ¸¯ 01'
  password: test123
  port: 443
  server: example-hk01.com
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 01'
  password: test123
  port: 443
  server: example-jp01.com
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01'
  password: test123
  port: 443
  server: example-sg01.com
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡ºğŸ‡¸ ç¾å›½ 01'
  password: test123
  port: 443
  server: example-us01.com
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡°ğŸ‡· éŸ©å›½ 01'
  password: test123
  port: 443
  server: example-kr01.com
  type: ss
  udp: true
proxy-groups:
- interval: 300
  name: ğŸŒ è‡ªåŠ¨é€‰æ‹©
  proxies: &id001
  - '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡­ğŸ‡° é¦™æ¸¯ 01'
  - '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 01'
  - '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01'
  - '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡ºğŸ‡¸ ç¾å›½ 01'
  - '[å¤©ç©ºåŠ é€Ÿå™¨] ğŸ‡°ğŸ‡· éŸ©å›½ 01'
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  proxies: *id001
  type: select
rules:
- MATCH,ğŸŒ è‡ªåŠ¨é€‰æ‹©
